services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
