services:
  neo4j:
    image: "neo4j:latest"
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    networks:
      - app_network
    ports:
      - "7687:7687"
      - "7474:7474"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'cypher-shell -u "$NEO4J_USERNAME" -p "$NEO4J_PASSWORD" "RETURN 1"',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  app_network:
    driver: bridge
